### ISSUE TITLE
How to run migrations in Github Actions using firebase token?

### ISSUE THREAD

**Issue by adinvadim** [kevlened/fireway#52]
I got firebase token by using command `firebase login:ci`, and after deploy with flag `--token`

How to run migrations with this token?

**Comment by adinvadim** [comment]
@kevlened need your help

**Comment by yliu7810** [comment]
+1 I would like to know how to use this on firebase too. Thanks in advance!

**Comment by eugeneford** [comment]
@yliu7810 @adinvadim, I've managed to do this by creating the following workflow:

```yml
name: Migrate Firestore

on:
  push:
    branches:
      - your_branch

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.YOUR_GCLOUD_SERVICE_ACCOUNT_JSON_ENCODED_TO_BASE64 }}
      - name: Migrate data
        run: npm run migrations # this basically runs fireway migrate
```
